name: "Deploy Spectron"
on:
  push:
    branches:
      - main

jobs:
  PrintDeploymentStatus:
    runs-on: ubuntu-latest
    steps:
      - name: Print event trigger
        run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."

  DeployToRemote:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the remote server and execute git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd public_html \
            git pull
